Add basic poetry support
zehengl/pip-check-updates pull request #12
Opened 2022-04-18 12:12 UTC by nikolaik

This builds on the Pipfile checking support and adapts it to support poetry dependencies in `pyproject.toml`.

I manage projects using a mix of different package management tools pip (`requirements.txt`), pipenv and poetry, so having one tool to support them all would be a time saver for me.

2022-04-18 16:39 UTC, zehengl requested changes

2022-04-18 16:39 UTC, zehengl commented on pip_check_updates/__init__.py
> +            results.append(f"{key}=={val}")
in a `pyproject.toml` file, see [example](https://github.com/python-poetry/poetry/blob/dca0c562c42cb79a494eff982fc8a52c632100f4/pyproject.toml)

the `val` can be a string or dict-like object. I think the logic in `load_pipfile` still applies.

I would remove checking the `python` as a key since this can be done in the `pcufile` config.

According to the example aforementioned, we should add the [caret](https://python-poetry.org/docs/dependency-specification/#caret-requirements) in the `get_current_version()` function so that it can handle splitting the dependency name and version string.

```
   name, current_version = [token for token in re.split(r"[><=~!]", dep) if token]
```

2022-04-20 20:19 UTC, nikolaik commented on pip_check_updates/__init__.py
> +            results.append(f"{key}=={val}")
Hi @zehengl thanks for looking at my PR so fast. I tried to address your comments. Do they look ok to you? I left in the filtering of `python` dependency, since it's something all poetry `pyproject.toml`s have.

Do you want me to add a few tests with actual requirements files too?

2022-04-20 21:00 UTC, zehengl commented on pip_check_updates/__init__.py
> +            results.append(f"{key}=={val}")
Thanks for changes. LGTM 👍

2022-04-20 21:03 UTC, zehengl commented on pip_check_updates/__init__.py
> +            results.append(f"{key}=={val}")
BTW, feel free to add tests on a different PR. That's also on my todo list but I don't have time to work on it yet. Appreciate your contribution!

2022-04-20 21:04 UTC, merged

2022-04-20 21:05 UTC, zehengl commented
@all-contributors please add @nikolaik for code